### ISSUE TITLE
输入参数都没问题为什么还在提示

### ISSUE THREAD

**Issue by maye-gitch** [k-fire/fofa-tool#1]
![image](https://user-images.githubusercontent.com/74856276/212459114-f461c27f-df99-460f-9c67-bd74cdbb357f.png)

**Comment by k-fire** [comment]
兄弟 ，这是两年前的东西了，fofa的网址都变了哇

**Comment by k-fire** [comment]
https://github.com/k-fire/fofa-tool/commit/d99a9c9dec770de40f0bf5cf42a611968639df84
